# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from api.utils import globalserver_pb2 as api_dot_utils_dot_globalserver__pb2


class TaskControllerStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get_task_request = channel.unary_unary(
        '/globalserver.TaskController/get_task_request',
        request_serializer=api_dot_utils_dot_globalserver__pb2.TaskRequest.SerializeToString,
        response_deserializer=api_dot_utils_dot_globalserver__pb2.TaskResponse.FromString,
        )
    self.fetch_model_request = channel.unary_stream(
        '/globalserver.TaskController/fetch_model_request',
        request_serializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.SerializeToString,
        response_deserializer=api_dot_utils_dot_globalserver__pb2.Model.FromString,
        )
    self.train_model_response = channel.unary_unary(
        '/globalserver.TaskController/train_model_response',
        request_serializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.SerializeToString,
        response_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.FromString,
        )
    self.send_model_update_response = channel.stream_unary(
        '/globalserver.TaskController/send_model_update_response',
        request_serializer=api_dot_utils_dot_globalserver__pb2.ModelUpdate.SerializeToString,
        response_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.FromString,
        )
    self.send_datasets = channel.unary_unary(
        '/globalserver.TaskController/send_datasets',
        request_serializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.SerializeToString,
        response_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.FromString,
        )
    self.send_validation_loss_response = channel.unary_unary(
        '/globalserver.TaskController/send_validation_loss_response',
        request_serializer=api_dot_utils_dot_globalserver__pb2.Loss.SerializeToString,
        response_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.FromString,
        )
    self.send_train_loss_response = channel.unary_unary(
        '/globalserver.TaskController/send_train_loss_response',
        request_serializer=api_dot_utils_dot_globalserver__pb2.Loss.SerializeToString,
        response_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.FromString,
        )
    self.send_test_loss_response = channel.unary_unary(
        '/globalserver.TaskController/send_test_loss_response',
        request_serializer=api_dot_utils_dot_globalserver__pb2.Loss.SerializeToString,
        response_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.FromString,
        )
    self.test_connection = channel.unary_unary(
        '/globalserver.TaskController/test_connection',
        request_serializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.SerializeToString,
        response_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.FromString,
        )
    self.stopped_experiment_response = channel.unary_unary(
        '/globalserver.TaskController/stopped_experiment_response',
        request_serializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.SerializeToString,
        response_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.FromString,
        )
    self.failed_experiment_response = channel.unary_unary(
        '/globalserver.TaskController/failed_experiment_response',
        request_serializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.SerializeToString,
        response_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.FromString,
        )
    self.stop_experiment = channel.unary_unary(
        '/globalserver.TaskController/stop_experiment',
        request_serializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.SerializeToString,
        response_deserializer=api_dot_utils_dot_globalserver__pb2.ExperimentResponse.FromString,
        )
    self.start_experiment = channel.unary_unary(
        '/globalserver.TaskController/start_experiment',
        request_serializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.SerializeToString,
        response_deserializer=api_dot_utils_dot_globalserver__pb2.ExperimentResponse.FromString,
        )
    self.get_latest_global_model = channel.unary_unary(
        '/globalserver.TaskController/get_latest_global_model',
        request_serializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.SerializeToString,
        response_deserializer=api_dot_utils_dot_globalserver__pb2.ModelIdResponse.FromString,
        )


class TaskControllerServicer(object):
  """The greeting service definition.
  """

  def get_task_request(self, request, context):
    """For Node Worker
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def fetch_model_request(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def train_model_response(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def send_model_update_response(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def send_datasets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def send_validation_loss_response(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def send_train_loss_response(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def send_test_loss_response(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def test_connection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stopped_experiment_response(self, request, context):
    """For Node Controller
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def failed_experiment_response(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stop_experiment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def start_experiment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_latest_global_model(self, request, context):
    """For Predictor
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TaskControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get_task_request': grpc.unary_unary_rpc_method_handler(
          servicer.get_task_request,
          request_deserializer=api_dot_utils_dot_globalserver__pb2.TaskRequest.FromString,
          response_serializer=api_dot_utils_dot_globalserver__pb2.TaskResponse.SerializeToString,
      ),
      'fetch_model_request': grpc.unary_stream_rpc_method_handler(
          servicer.fetch_model_request,
          request_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.FromString,
          response_serializer=api_dot_utils_dot_globalserver__pb2.Model.SerializeToString,
      ),
      'train_model_response': grpc.unary_unary_rpc_method_handler(
          servicer.train_model_response,
          request_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.FromString,
          response_serializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.SerializeToString,
      ),
      'send_model_update_response': grpc.stream_unary_rpc_method_handler(
          servicer.send_model_update_response,
          request_deserializer=api_dot_utils_dot_globalserver__pb2.ModelUpdate.FromString,
          response_serializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.SerializeToString,
      ),
      'send_datasets': grpc.unary_unary_rpc_method_handler(
          servicer.send_datasets,
          request_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.FromString,
          response_serializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.SerializeToString,
      ),
      'send_validation_loss_response': grpc.unary_unary_rpc_method_handler(
          servicer.send_validation_loss_response,
          request_deserializer=api_dot_utils_dot_globalserver__pb2.Loss.FromString,
          response_serializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.SerializeToString,
      ),
      'send_train_loss_response': grpc.unary_unary_rpc_method_handler(
          servicer.send_train_loss_response,
          request_deserializer=api_dot_utils_dot_globalserver__pb2.Loss.FromString,
          response_serializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.SerializeToString,
      ),
      'send_test_loss_response': grpc.unary_unary_rpc_method_handler(
          servicer.send_test_loss_response,
          request_deserializer=api_dot_utils_dot_globalserver__pb2.Loss.FromString,
          response_serializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.SerializeToString,
      ),
      'test_connection': grpc.unary_unary_rpc_method_handler(
          servicer.test_connection,
          request_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.FromString,
          response_serializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.SerializeToString,
      ),
      'stopped_experiment_response': grpc.unary_unary_rpc_method_handler(
          servicer.stopped_experiment_response,
          request_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.FromString,
          response_serializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.SerializeToString,
      ),
      'failed_experiment_response': grpc.unary_unary_rpc_method_handler(
          servicer.failed_experiment_response,
          request_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.FromString,
          response_serializer=api_dot_utils_dot_globalserver__pb2.DefaultResponse.SerializeToString,
      ),
      'stop_experiment': grpc.unary_unary_rpc_method_handler(
          servicer.stop_experiment,
          request_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.FromString,
          response_serializer=api_dot_utils_dot_globalserver__pb2.ExperimentResponse.SerializeToString,
      ),
      'start_experiment': grpc.unary_unary_rpc_method_handler(
          servicer.start_experiment,
          request_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.FromString,
          response_serializer=api_dot_utils_dot_globalserver__pb2.ExperimentResponse.SerializeToString,
      ),
      'get_latest_global_model': grpc.unary_unary_rpc_method_handler(
          servicer.get_latest_global_model,
          request_deserializer=api_dot_utils_dot_globalserver__pb2.DefaultRequest.FromString,
          response_serializer=api_dot_utils_dot_globalserver__pb2.ModelIdResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'globalserver.TaskController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
